name: "Terraform Plan (Infra)"
on: [push]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init (no backend)
        run: |
          cd terraform-aws-infra/environments/dev
          terraform init -backend=false
      - name: Terraform Validate
        run: |
          cd terraform-aws-infra/environments/dev
          terraform validate
      - name: Terraform Plan
        run: |
          cd terraform-aws-infra/environments/dev
          terraform plan -out=tfplan
